/**
 * Built-in UK merchant dictionary.
 *
 * Each entry maps an UPPERCASE substring `pattern` to a seeded category `name`
 * (exact spelling from prisma/seed.ts — renaming a seeded category breaks
 * these). Patterns are matched as case-sensitive substrings against the
 * *normalised* description produced by normalizeDescription().
 *
 * MATCH ORDERING: categorize() sorts ALL patterns (these + user rules)
 * longest-first, so more specific patterns win regardless of their position
 * here. The grouping below is for human readability only. Where two brands
 * collide as substrings (e.g. "UBER EATS" vs "UBER", "TESCO PETROL" vs
 * "TESCO"), the longer, more specific pattern is listed and naturally wins the
 * length sort.
 *
 * AMBIGUITY DECISIONS (documented per the build prompt):
 *  - Plain "BP" is too short / collides with the bank "BP" (bill payment)
 *    prefix and words like "BP" inside refs. We only match fuel-specific
 *    variants: "BP CONNECT", "BP FUEL", and "BP " with a trailing space (so a
 *    description body like "BP GARAGE ..." matches but a bare leading prefix,
 *    already stripped by normalize, does not).
 *  - Plain "VUE" collides with words; we match "VUE CINEMA" and
 *    "VUE ENTERTAINMENT" only.
 *  - "COUNCIL" alone is ambiguous (could appear in unrelated text) but the
 *    common bank rendering "X COUNCIL" for council-tax direct debits is worth
 *    catching, so we include "COUNCIL" → Council Tax in addition to the
 *    explicit "COUNCIL TAX"/"CTAX"/"COUNCILTAX". Longest-first means
 *    "COUNCIL TAX" wins when both could match.
 *  - "RENT" is risky (substring of "PARENT", "CURRENT", "DIFFERENT"); we keep
 *    it but rely on it being a weak/short pattern that user rules can override.
 *  - DVLA vehicle tax has no perfect home; vehicle tax is a motoring/regulatory
 *    cost — filed under "Insurance" (closest motoring-admin bucket), documented
 *    here so reviewers know it was a deliberate choice.
 */

import type { UserRule } from "@/lib/types";

export interface MerchantEntry {
  /** UPPERCASE substring matched against the normalised description. */
  pattern: string;
  /** Seeded category NAME (see prisma/seed.ts). */
  category: string;
}

export const UK_MERCHANTS: MerchantEntry[] = [
  // ───────────────────────── Groceries ─────────────────────────
  // Petrol/fuel & mobile sub-brands are listed in their own sections and win
  // by length over the bare supermarket name.
  { pattern: "TESCO EXPRESS", category: "Groceries" },
  { pattern: "TESCO METRO", category: "Groceries" },
  { pattern: "TESCO STORES", category: "Groceries" },
  { pattern: "TESCO SUPERSTORE", category: "Groceries" },
  { pattern: "TESCO", category: "Groceries" },
  { pattern: "SAINSBURYS LOCAL", category: "Groceries" },
  { pattern: "SAINSBURYS", category: "Groceries" },
  { pattern: "SAINSBURY", category: "Groceries" },
  { pattern: "ASDA SUPERSTORE", category: "Groceries" },
  { pattern: "ASDA STORES", category: "Groceries" },
  { pattern: "ASDA", category: "Groceries" },
  { pattern: "MORRISONS DAILY", category: "Groceries" },
  { pattern: "MORRISONS", category: "Groceries" },
  { pattern: "ALDI", category: "Groceries" },
  { pattern: "LIDL", category: "Groceries" },
  { pattern: "WAITROSE", category: "Groceries" },
  { pattern: "M&S SIMPLY FOOD", category: "Groceries" },
  { pattern: "MARKS & SPENCER FOOD", category: "Groceries" },
  { pattern: "ICELAND FOODS", category: "Groceries" },
  { pattern: "ICELAND", category: "Groceries" },
  { pattern: "OCADO", category: "Groceries" },
  { pattern: "FARMFOODS", category: "Groceries" },
  { pattern: "BOOTHS", category: "Groceries" },
  { pattern: "THE CO-OPERATIVE FOOD", category: "Groceries" },
  { pattern: "CO-OP FOOD", category: "Groceries" },
  { pattern: "COOP FOOD", category: "Groceries" },
  { pattern: "CO-OP", category: "Groceries" },
  { pattern: "COOP", category: "Groceries" },
  { pattern: "SPAR", category: "Groceries" },
  { pattern: "COSTCUTTER", category: "Groceries" },
  { pattern: "NISA LOCAL", category: "Groceries" },
  { pattern: "NISA", category: "Groceries" },
  { pattern: "PREMIER STORES", category: "Groceries" },
  { pattern: "LONDIS", category: "Groceries" },
  { pattern: "BUDGENS", category: "Groceries" },
  { pattern: "GETIR", category: "Groceries" },
  { pattern: "GORILLAS", category: "Groceries" },
  { pattern: "WHOLE FOODS", category: "Groceries" },
  { pattern: "BOOKER", category: "Groceries" },
  { pattern: "PLANET ORGANIC", category: "Groceries" },
  { pattern: "FRUITY FRESH", category: "Groceries" },
  { pattern: "NITA CASH AND CARRY", category: "Groceries" },
  { pattern: "GANAPATHY CASH AND CARRY", category: "Groceries" },
  { pattern: "GANAPATHY CASH CARRY", category: "Groceries" },
  { pattern: "GANAPATHY CASH & CARRY", category: "Groceries" },
  { pattern: "FUDCO", category: "Groceries" },

  // ───────────────────────── Coffee & Snacks ─────────────────────────
  { pattern: "COSTA COFFEE", category: "Coffee & Snacks" },
  { pattern: "COSTA", category: "Coffee & Snacks" },
  { pattern: "STARBUCKS", category: "Coffee & Snacks" },
  { pattern: "CAFFE NERO", category: "Coffee & Snacks" },
  { pattern: "CAFE NERO", category: "Coffee & Snacks" },
  { pattern: "NERO", category: "Coffee & Snacks" },
  { pattern: "PRET A MANGER", category: "Coffee & Snacks" },
  { pattern: "PRET", category: "Coffee & Snacks" },
  { pattern: "GREGGS", category: "Coffee & Snacks" },
  { pattern: "GAILS BAKERY", category: "Coffee & Snacks" },
  { pattern: "GAILS", category: "Coffee & Snacks" },
  { pattern: "KRISPY KREME", category: "Coffee & Snacks" },
  { pattern: "DUNKIN", category: "Coffee & Snacks" },
  { pattern: "PAUL BAKERY", category: "Coffee & Snacks" },
  { pattern: "PATISSERIE VALERIE", category: "Coffee & Snacks" },
  { pattern: "BLACK SHEEP COFFEE", category: "Coffee & Snacks" },
  { pattern: "JOE & THE JUICE", category: "Coffee & Snacks" },
  { pattern: "INSOMNIA COFFEE", category: "Coffee & Snacks" },
  { pattern: "MILLIES COOKIES", category: "Coffee & Snacks" },
  { pattern: "TIM HORTONS", category: "Coffee & Snacks" },

  // ───────────────────────── Eating Out ─────────────────────────
  // Food-delivery aggregators + sit-down + fast food. "UBER EATS" MUST precede
  // "UBER" (Transport) — handled by length sort.
  { pattern: "UBER EATS", category: "Eating Out" },
  { pattern: "UBEREATS", category: "Eating Out" },
  { pattern: "MCDELIVERY", category: "Eating Out" },
  { pattern: "DELIVEROO", category: "Eating Out" },
  { pattern: "JUST EAT", category: "Eating Out" },
  { pattern: "JUST-EAT", category: "Eating Out" },
  { pattern: "JUSTEAT", category: "Eating Out" },
  { pattern: "MCDONALD", category: "Eating Out" },
  { pattern: "KFC", category: "Eating Out" },
  { pattern: "BURGER KING", category: "Eating Out" },
  { pattern: "NANDO", category: "Eating Out" },
  { pattern: "PIZZA EXPRESS", category: "Eating Out" },
  { pattern: "PIZZA HUT", category: "Eating Out" },
  { pattern: "DOMINO", category: "Eating Out" },
  { pattern: "PAPA JOHN", category: "Eating Out" },
  { pattern: "SUBWAY", category: "Eating Out" },
  { pattern: "WAGAMAMA", category: "Eating Out" },
  { pattern: "FIVE GUYS", category: "Eating Out" },
  { pattern: "TGI FRIDAY", category: "Eating Out" },
  { pattern: "WETHERSPOON", category: "Eating Out" },
  { pattern: "TOBY CARVERY", category: "Eating Out" },
  { pattern: "HARVESTER", category: "Eating Out" },
  { pattern: "ZIZZI", category: "Eating Out" },
  { pattern: "ASK ITALIAN", category: "Eating Out" },
  { pattern: "PREZZO", category: "Eating Out" },
  { pattern: "BELLA ITALIA", category: "Eating Out" },
  { pattern: "FRANKIE & BENNY", category: "Eating Out" },
  { pattern: "LEON", category: "Eating Out" },
  { pattern: "ITSU", category: "Eating Out" },
  { pattern: "WASABI", category: "Eating Out" },
  { pattern: "YO SUSHI", category: "Eating Out" },
  { pattern: "YO! SUSHI", category: "Eating Out" },
  { pattern: "GBK", category: "Eating Out" },
  { pattern: "GOURMET BURGER", category: "Eating Out" },
  { pattern: "BYRON", category: "Eating Out" },
  { pattern: "TACO BELL", category: "Eating Out" },
  { pattern: "CHIQUITO", category: "Eating Out" },
  { pattern: "MILLER & CARTER", category: "Eating Out" },
  { pattern: "BEEFEATER", category: "Eating Out" },
  { pattern: "PIZZA PILGRIMS", category: "Eating Out" },
  { pattern: "FRANCO MANCA", category: "Eating Out" },
  { pattern: "HONEST BURGER", category: "Eating Out" },
  { pattern: "TORTILLA", category: "Eating Out" },
  { pattern: "CHOPSTIX", category: "Eating Out" },
  { pattern: "WIMPY", category: "Eating Out" },
  { pattern: "POPEYES", category: "Eating Out" },
  { pattern: "GERMAN DONER", category: "Eating Out" },
  { pattern: "BREWDOG", category: "Eating Out" },
  { pattern: "SLUG & LETTUCE", category: "Eating Out" },
  { pattern: "ALL BAR ONE", category: "Eating Out" },
  { pattern: "GREENE KING", category: "Eating Out" },
  { pattern: "STONEHOUSE", category: "Eating Out" },
  { pattern: "VINTAGE INN", category: "Eating Out" },
  { pattern: "FISH & CHIP", category: "Eating Out" },

  // ───────────────────────── Transport ─────────────────────────
  // Plain "UBER" sits AFTER "UBER EATS" by length; rail operators and ride/
  // micro-mobility brands grouped here.
  { pattern: "TRANSPORT FOR LONDON", category: "Transport" },
  { pattern: "TFL TRAVEL", category: "Transport" },
  { pattern: "TFL", category: "Transport" },
  { pattern: "OYSTER", category: "Transport" },
  { pattern: "TRAINLINE", category: "Transport" },
  { pattern: "NATIONAL RAIL", category: "Transport" },
  { pattern: "SOUTH WESTERN RAILWAY", category: "Transport" },
  { pattern: "EAST MIDLANDS RAILWAY", category: "Transport" },
  { pattern: "ELIZABETH LINE", category: "Transport" },
  { pattern: "NORTHERN RAIL", category: "Transport" },
  { pattern: "SOUTHERN RAIL", category: "Transport" },
  { pattern: "SOUTHEASTERN", category: "Transport" },
  { pattern: "THAMESLINK", category: "Transport" },
  { pattern: "MERSEYRAIL", category: "Transport" },
  { pattern: "SCOTRAIL", category: "Transport" },
  { pattern: "TRANSPENNINE", category: "Transport" },
  { pattern: "CROSSCOUNTRY", category: "Transport" },
  { pattern: "GREATER ANGLIA", category: "Transport" },
  { pattern: "AVANTI", category: "Transport" },
  { pattern: "LNER", category: "Transport" },
  { pattern: "GWR", category: "Transport" },
  { pattern: "SWR", category: "Transport" },
  { pattern: "C2C RAIL", category: "Transport" },
  { pattern: "CHILTERN RAILWAY", category: "Transport" },
  { pattern: "ADDISON LEE", category: "Transport" },
  { pattern: "FREE NOW", category: "Transport" },
  { pattern: "FREENOW", category: "Transport" },
  { pattern: "NATIONAL EXPRESS", category: "Transport" },
  { pattern: "STAGECOACH", category: "Transport" },
  { pattern: "FIRST BUS", category: "Transport" },
  { pattern: "ARRIVA", category: "Transport" },
  { pattern: "MEGABUS", category: "Transport" },
  { pattern: "RINGGO", category: "Transport" },
  { pattern: "JUSTPARK", category: "Transport" },
  { pattern: "PARKING", category: "Transport" },
  { pattern: "NCP", category: "Transport" },
  { pattern: "DART CHARGE", category: "Transport" },
  { pattern: "CONGESTION CHARGE", category: "Transport" },
  { pattern: "DVSA", category: "Transport" },
  { pattern: "UBER", category: "Transport" },
  { pattern: "BOLT", category: "Transport" },
  { pattern: "LIME", category: "Transport" },
  { pattern: "VOI", category: "Transport" },
  { pattern: "TIER", category: "Transport" },
  { pattern: "ZIPCAR", category: "Transport" },
  { pattern: "ENTERPRISE RENT", category: "Transport" },
  { pattern: "HERTZ", category: "Transport" },
  { pattern: "AVIS", category: "Transport" },
  { pattern: "EUROPCAR", category: "Transport" },

  // ───────────────────────── Fuel ─────────────────────────
  // Supermarket petrol stations win by length over the grocery name.
  { pattern: "TESCO PETROL", category: "Fuel" },
  { pattern: "TESCO PFS", category: "Fuel" },
  { pattern: "TESCO FUEL", category: "Fuel" },
  { pattern: "SAINSBURYS PETROL", category: "Fuel" },
  { pattern: "SAINSBURY PETROL", category: "Fuel" },
  { pattern: "ASDA PETROL", category: "Fuel" },
  { pattern: "ASDA FUEL", category: "Fuel" },
  { pattern: "MORRISONS PETROL", category: "Fuel" },
  { pattern: "MORRISONS PFS", category: "Fuel" },
  { pattern: "SHELL", category: "Fuel" },
  { pattern: "ESSO", category: "Fuel" },
  { pattern: "BP CONNECT", category: "Fuel" },
  { pattern: "BP FUEL", category: "Fuel" },
  { pattern: "BP GARAGE", category: "Fuel" },
  { pattern: "BP ", category: "Fuel" }, // trailing space — see ambiguity note
  { pattern: "TEXACO", category: "Fuel" },
  { pattern: "GULF OIL", category: "Fuel" },
  { pattern: "JET PETROL", category: "Fuel" },
  { pattern: "APPLEGREEN", category: "Fuel" },
  { pattern: "MOTO SERVICE", category: "Fuel" },
  { pattern: "EUROGARAGES", category: "Fuel" },
  { pattern: "MOTOR FUEL GROUP", category: "Fuel" },
  { pattern: "FILLING STATION", category: "Fuel" },
  { pattern: "SERVICE STATION", category: "Fuel" },
  { pattern: "PETROL", category: "Fuel" },
  { pattern: "INSTAVOLT", category: "Fuel" },
  { pattern: "PODPOINT", category: "Fuel" },
  { pattern: "POD POINT", category: "Fuel" },
  { pattern: "GRIDSERVE", category: "Fuel" },
  { pattern: "BP PULSE", category: "Fuel" },

  // ───────────────────────── Shopping ─────────────────────────
  // "AMAZON PRIME"/"PRIME VIDEO" → Subscriptions (below) win by length.
  { pattern: "AMAZON MARKETPLACE", category: "Shopping" },
  { pattern: "DIESEL", category: "Shopping" },
  { pattern: "AMAZON MKTP", category: "Shopping" },
  { pattern: "AMZNMKTPLACE", category: "Shopping" },
  { pattern: "AMZN MKTP", category: "Shopping" },
  { pattern: "AMAZON.CO.UK", category: "Shopping" },
  { pattern: "AMAZON", category: "Shopping" },
  { pattern: "AMZN", category: "Shopping" },
  { pattern: "EBAY", category: "Shopping" },
  { pattern: "ARGOS", category: "Shopping" },
  { pattern: "JOHN LEWIS", category: "Shopping" },
  { pattern: "CURRYS", category: "Shopping" },
  { pattern: "THE RANGE", category: "Shopping" },
  { pattern: "WILKO", category: "Shopping" },
  { pattern: "HOME BARGAINS", category: "Shopping" },
  { pattern: "B&M", category: "Shopping" },
  { pattern: "POUNDLAND", category: "Shopping" },
  { pattern: "POUNDSTRETCHER", category: "Shopping" },
  { pattern: "TK MAXX", category: "Shopping" },
  { pattern: "TKMAXX", category: "Shopping" },
  { pattern: "HOMESENSE", category: "Shopping" },
  { pattern: "SPORTS DIRECT", category: "Shopping" },
  { pattern: "JD SPORTS", category: "Shopping" },
  { pattern: "DECATHLON", category: "Shopping" },
  { pattern: "SMYTHS", category: "Shopping" },
  { pattern: "THE WORKS", category: "Shopping" },
  { pattern: "WHSMITH", category: "Shopping" },
  { pattern: "WH SMITH", category: "Shopping" },
  { pattern: "WATERSTONES", category: "Shopping" },
  { pattern: "CARD FACTORY", category: "Shopping" },
  { pattern: "ETSY", category: "Shopping" },
  { pattern: "TEMU", category: "Shopping" },
  { pattern: "VINTED", category: "Shopping" },
  { pattern: "ROBERT DYAS", category: "Shopping" },
  { pattern: "RYMAN", category: "Shopping" },
  { pattern: "HOBBYCRAFT", category: "Shopping" },
  { pattern: "FLANNELS", category: "Shopping" },
  { pattern: "SELFRIDGES", category: "Shopping" },
  { pattern: "HARRODS", category: "Shopping" },
  { pattern: "FENWICK", category: "Shopping" },
  { pattern: "ALIEXPRESS", category: "Shopping" },
  { pattern: "WISH.COM", category: "Shopping" },
  { pattern: "MENKIND", category: "Shopping" },
  { pattern: "PADDY POWER", category: "Shopping" },
  { pattern: "GAME.CO.UK", category: "Shopping" },
  { pattern: "GAME STORE", category: "Shopping" },
  { pattern: "MAPLIN", category: "Shopping" },
  { pattern: "RICHER SOUNDS", category: "Shopping" },
  { pattern: "AO.COM", category: "Shopping" },
  { pattern: "VERY.CO.UK", category: "Shopping" },
  { pattern: "LITTLEWOODS", category: "Shopping" },
  { pattern: "STUDIO.CO.UK", category: "Shopping" },
  { pattern: "TIGER STORE", category: "Shopping" },
  { pattern: "FLYING TIGER", category: "Shopping" },
  { pattern: "PEPCO", category: "Shopping" },

  // ───────────────────────── Clothing ─────────────────────────
  { pattern: "PRIMARK", category: "Clothing" },
  { pattern: "NEXT RETAIL", category: "Clothing" },
  { pattern: "NEXT PLC", category: "Clothing" },
  { pattern: "ZARA", category: "Clothing" },
  { pattern: "H&M", category: "Clothing" },
  { pattern: "ASOS", category: "Clothing" },
  { pattern: "UNIQLO", category: "Clothing" },
  { pattern: "RIVER ISLAND", category: "Clothing" },
  { pattern: "NEW LOOK", category: "Clothing" },
  { pattern: "MATALAN", category: "Clothing" },
  { pattern: "BOOHOO", category: "Clothing" },
  { pattern: "SHEIN", category: "Clothing" },
  { pattern: "MANGO", category: "Clothing" },
  { pattern: "GAP", category: "Clothing" },
  { pattern: "FAT FACE", category: "Clothing" },
  { pattern: "WHITE STUFF", category: "Clothing" },
  { pattern: "JOULES", category: "Clothing" },
  { pattern: "SUPERDRY", category: "Clothing" },
  { pattern: "SCHUH", category: "Clothing" },
  { pattern: "CLARKS", category: "Clothing" },
  { pattern: "OFFICE SHOES", category: "Clothing" },
  { pattern: "FOOT LOCKER", category: "Clothing" },
  { pattern: "FOOTLOCKER", category: "Clothing" },
  { pattern: "MARKS & SPENCER", category: "Clothing" }, // non-food M&S after the food variant
  { pattern: "M&S", category: "Clothing" },
  { pattern: "DOROTHY PERKINS", category: "Clothing" },
  { pattern: "TOPSHOP", category: "Clothing" },
  { pattern: "BURTON", category: "Clothing" },
  { pattern: "PEACOCKS", category: "Clothing" },
  { pattern: "BONMARCHE", category: "Clothing" },
  { pattern: "JACK WILLS", category: "Clothing" },
  { pattern: "HOLLISTER", category: "Clothing" },
  { pattern: "ABERCROMBIE", category: "Clothing" },
  { pattern: "PULL & BEAR", category: "Clothing" },
  { pattern: "BERSHKA", category: "Clothing" },
  { pattern: "MASSIMO DUTTI", category: "Clothing" },
  { pattern: "REISS", category: "Clothing" },
  { pattern: "TED BAKER", category: "Clothing" },
  { pattern: "ALL SAINTS", category: "Clothing" },
  { pattern: "ALLSAINTS", category: "Clothing" },
  { pattern: "NIKE", category: "Clothing" },
  { pattern: "ADIDAS", category: "Clothing" },
  { pattern: "DR MARTENS", category: "Clothing" },
  { pattern: "SIZE?", category: "Clothing" },
  { pattern: "TESSUTI", category: "Clothing" },
  { pattern: "MOSS BROS", category: "Clothing" },

  // ───────────────────────── Health & Pharmacy ─────────────────────────
  { pattern: "BOOTS", category: "Health & Pharmacy" },
  { pattern: "SUPERDRUG", category: "Health & Pharmacy" },
  { pattern: "LLOYDS PHARMACY", category: "Health & Pharmacy" },
  { pattern: "WELL PHARMACY", category: "Health & Pharmacy" },
  { pattern: "ROWLANDS PHARMACY", category: "Health & Pharmacy" },
  { pattern: "PHARMACY", category: "Health & Pharmacy" },
  { pattern: "HOLLAND & BARRETT", category: "Health & Pharmacy" },
  { pattern: "SPECSAVERS", category: "Health & Pharmacy" },
  { pattern: "VISION EXPRESS", category: "Health & Pharmacy" },
  { pattern: "BOOTS OPTICIAN", category: "Health & Pharmacy" },
  { pattern: "BUPA", category: "Health & Pharmacy" },
  { pattern: "NUFFIELD HEALTH", category: "Health & Pharmacy" },
  { pattern: "NUFFIELD", category: "Health & Pharmacy" },
  { pattern: "PUREGYM", category: "Health & Pharmacy" },
  { pattern: "PURE GYM", category: "Health & Pharmacy" },
  { pattern: "THE GYM GROUP", category: "Health & Pharmacy" },
  { pattern: "DAVID LLOYD", category: "Health & Pharmacy" },
  { pattern: "VIRGIN ACTIVE", category: "Health & Pharmacy" },
  { pattern: "ANYTIME FITNESS", category: "Health & Pharmacy" },
  { pattern: "JD GYM", category: "Health & Pharmacy" },
  { pattern: "BANNATYNE", category: "Health & Pharmacy" },
  { pattern: "FITNESS FIRST", category: "Health & Pharmacy" },
  { pattern: "NHS", category: "Health & Pharmacy" },
  { pattern: "DENTAL", category: "Health & Pharmacy" },
  { pattern: "DENTIST", category: "Health & Pharmacy" },
  { pattern: "OPTICIANS", category: "Health & Pharmacy" },

  // ───────────────────────── Entertainment ─────────────────────────
  { pattern: "CINEWORLD", category: "Entertainment" },
  { pattern: "ODEON", category: "Entertainment" },
  { pattern: "VUE CINEMA", category: "Entertainment" },
  { pattern: "VUE ENTERTAINMENT", category: "Entertainment" },
  { pattern: "PICTUREHOUSE", category: "Entertainment" },
  { pattern: "EVERYMAN", category: "Entertainment" },
  { pattern: "TICKETMASTER", category: "Entertainment" },
  { pattern: "SEE TICKETS", category: "Entertainment" },
  { pattern: "EVENTIM", category: "Entertainment" },
  { pattern: "AXS", category: "Entertainment" },
  { pattern: "SKIDDLE", category: "Entertainment" },
  { pattern: "DICE.FM", category: "Entertainment" },
  { pattern: "STEAM GAMES", category: "Entertainment" },
  { pattern: "STEAMGAMES", category: "Entertainment" },
  { pattern: "EPIC GAMES", category: "Entertainment" },
  { pattern: "HOLLYWOOD BOWL", category: "Entertainment" },
  { pattern: "TENPIN", category: "Entertainment" },
  { pattern: "BOWLING", category: "Entertainment" },
  { pattern: "ALL STAR LANES", category: "Entertainment" },
  { pattern: "GOLD'S GYM", category: "Entertainment" },
  { pattern: "MERLIN ENTERTAINMENT", category: "Entertainment" },
  { pattern: "ALTON TOWERS", category: "Entertainment" },
  { pattern: "THORPE PARK", category: "Entertainment" },
  { pattern: "LEGOLAND", category: "Entertainment" },
  { pattern: "CHESSINGTON", category: "Entertainment" },
  { pattern: "ZSL", category: "Entertainment" },
  { pattern: "ESCAPE ROOM", category: "Entertainment" },
  { pattern: "LASER QUEST", category: "Entertainment" },
  { pattern: "GO APE", category: "Entertainment" },
  { pattern: "NATIONAL TRUST", category: "Entertainment" },
  { pattern: "ENGLISH HERITAGE", category: "Entertainment" },
  { pattern: "TROVE", category: "Entertainment" },

  // ───────────────────────── Subscriptions ─────────────────────────
  // These outrank Shopping/Health brands of the same root by length, e.g.
  // "AMAZON PRIME" beats "AMAZON".
  { pattern: "NETFLIX", category: "Subscriptions" },
  { pattern: "SPOTIFY", category: "Subscriptions" },
  { pattern: "DISNEY PLUS", category: "Subscriptions" },
  { pattern: "DISNEY+", category: "Subscriptions" },
  { pattern: "DISNEYPLUS", category: "Subscriptions" },
  { pattern: "AMAZON PRIME", category: "Subscriptions" },
  { pattern: "PRIME VIDEO", category: "Subscriptions" },
  { pattern: "AMAZON MUSIC", category: "Subscriptions" },
  { pattern: "NOW TV", category: "Subscriptions" },
  { pattern: "APPLE.COM/BILL", category: "Subscriptions" },
  { pattern: "APPLE.COM BILL", category: "Subscriptions" },
  { pattern: "ITUNES.COM", category: "Subscriptions" },
  { pattern: "YOUTUBE PREMIUM", category: "Subscriptions" },
  { pattern: "YOUTUBEPREMIUM", category: "Subscriptions" },
  { pattern: "YOUTUBE MUSIC", category: "Subscriptions" },
  { pattern: "GOOGLE YOUTUBE", category: "Subscriptions" },
  { pattern: "AUDIBLE", category: "Subscriptions" },
  { pattern: "KINDLE UNLIMITED", category: "Subscriptions" },
  { pattern: "KINDLE UNLTD", category: "Subscriptions" },
  { pattern: "XBOX", category: "Subscriptions" },
  { pattern: "PLAYSTATION", category: "Subscriptions" },
  { pattern: "PLAYSTATIONNETWORK", category: "Subscriptions" },
  { pattern: "NINTENDO", category: "Subscriptions" },
  { pattern: "ADOBE", category: "Subscriptions" },
  { pattern: "MICROSOFT 365", category: "Subscriptions" },
  { pattern: "MICROSOFT", category: "Subscriptions" },
  { pattern: "MSFT", category: "Subscriptions" },
  { pattern: "ICLOUD", category: "Subscriptions" },
  { pattern: "GOOGLE ONE", category: "Subscriptions" },
  { pattern: "GOOGLE STORAGE", category: "Subscriptions" },
  { pattern: "DROPBOX", category: "Subscriptions" },
  { pattern: "CANVA", category: "Subscriptions" },
  { pattern: "CHATGPT", category: "Subscriptions" },
  { pattern: "OPENAI", category: "Subscriptions" },
  { pattern: "CLAUDE.AI", category: "Subscriptions" },
  { pattern: "ANTHROPIC", category: "Subscriptions" },
  { pattern: "PATREON", category: "Subscriptions" },
  { pattern: "SUBSTACK", category: "Subscriptions" },
  { pattern: "DAZN", category: "Subscriptions" },
  { pattern: "TWITCH", category: "Subscriptions" },
  { pattern: "PARAMOUNT+", category: "Subscriptions" },
  { pattern: "PARAMOUNT PLUS", category: "Subscriptions" },
  { pattern: "APPLE TV", category: "Subscriptions" },
  { pattern: "APPLE MUSIC", category: "Subscriptions" },
  { pattern: "DEEZER", category: "Subscriptions" },
  { pattern: "TIDAL", category: "Subscriptions" },
  { pattern: "AUDIOBOOKS.COM", category: "Subscriptions" },
  { pattern: "BRITBOX", category: "Subscriptions" },
  { pattern: "CRUNCHYROLL", category: "Subscriptions" },
  { pattern: "MUBI", category: "Subscriptions" },
  { pattern: "TV LICENCE", category: "Subscriptions" },
  { pattern: "TV LICENSING", category: "Subscriptions" },
  { pattern: "LINKEDIN", category: "Subscriptions" },
  { pattern: "NORDVPN", category: "Subscriptions" },
  { pattern: "EXPRESSVPN", category: "Subscriptions" },
  { pattern: "GOOGLE STADIA", category: "Subscriptions" },
  { pattern: "EA PLAY", category: "Subscriptions" },
  { pattern: "NOTION", category: "Subscriptions" },
  { pattern: "GRAMMARLY", category: "Subscriptions" },
  { pattern: "1PASSWORD", category: "Subscriptions" },
  { pattern: "STRAVA", category: "Subscriptions" },
  { pattern: "DUOLINGO PLUS", category: "Subscriptions" },

  // ───────────────────────── Utilities ─────────────────────────
  { pattern: "BRITISH GAS", category: "Utilities" },
  { pattern: "BRITISHGAS", category: "Utilities" },
  { pattern: "EDF ENERGY", category: "Utilities" },
  { pattern: "EDF", category: "Utilities" },
  { pattern: "E.ON NEXT", category: "Utilities" },
  { pattern: "EON NEXT", category: "Utilities" },
  { pattern: "E.ON", category: "Utilities" },
  { pattern: "E-ON", category: "Utilities" },
  { pattern: "OCTOPUS ENERGY", category: "Utilities" },
  { pattern: "OVO ENERGY", category: "Utilities" },
  { pattern: "SCOTTISH POWER", category: "Utilities" },
  { pattern: "SCOTTISHPOWER", category: "Utilities" },
  { pattern: "SHELL ENERGY", category: "Utilities" },
  { pattern: "UTILITY WAREHOUSE", category: "Utilities" },
  { pattern: "UTILITA", category: "Utilities" },
  { pattern: "BULB ENERGY", category: "Utilities" },
  { pattern: "GOOD ENERGY", category: "Utilities" },
  { pattern: "SSE", category: "Utilities" },
  { pattern: "THAMES WATER", category: "Utilities" },
  { pattern: "SEVERN TRENT", category: "Utilities" },
  { pattern: "UNITED UTILITIES", category: "Utilities" },
  { pattern: "ANGLIAN WATER", category: "Utilities" },
  { pattern: "YORKSHIRE WATER", category: "Utilities" },
  { pattern: "SOUTHERN WATER", category: "Utilities" },
  { pattern: "WESSEX WATER", category: "Utilities" },
  { pattern: "NORTHUMBRIAN WATER", category: "Utilities" },
  { pattern: "AFFINITY WATER", category: "Utilities" },
  { pattern: "SOUTH EAST WATER", category: "Utilities" },
  { pattern: "SOUTH WEST WATER", category: "Utilities" },
  { pattern: "WELSH WATER", category: "Utilities" },
  { pattern: "DWR CYMRU", category: "Utilities" },
  { pattern: "SCOTTISH WATER", category: "Utilities" },
  { pattern: "BRISTOL WATER", category: "Utilities" },
  { pattern: "SO ENERGY", category: "Utilities" },
  { pattern: "REBEL ENERGY", category: "Utilities" },
  { pattern: "ENERGY BILL", category: "Utilities" },

  // ───────────────────────── Council Tax ─────────────────────────
  { pattern: "COUNCIL TAX", category: "Council Tax" },
  { pattern: "COUNCILTAX", category: "Council Tax" },
  { pattern: "CTAX", category: "Council Tax" },
  { pattern: "C/TAX", category: "Council Tax" },
  { pattern: "COUNCIL", category: "Council Tax" }, // see ambiguity note

  // ───────────────────────── Rent & Mortgage ─────────────────────────
  { pattern: "MORTGAGE", category: "Rent & Mortgage" },
  { pattern: "NATIONWIDE MTG", category: "Rent & Mortgage" },
  { pattern: "HALIFAX MTG", category: "Rent & Mortgage" },
  { pattern: "SANTANDER MTG", category: "Rent & Mortgage" },
  { pattern: "BARCLAYS MORTGAGE", category: "Rent & Mortgage" },
  { pattern: "LETTINGS", category: "Rent & Mortgage" },
  { pattern: "LETTING AGENT", category: "Rent & Mortgage" },
  { pattern: "ESTATE AGENT", category: "Rent & Mortgage" },
  { pattern: "PROPERTY MANAGEMENT", category: "Rent & Mortgage" },
  { pattern: "HOUSING ASSOC", category: "Rent & Mortgage" },
  { pattern: "RENT", category: "Rent & Mortgage" }, // see ambiguity note

  // ───────────────────────── Insurance ─────────────────────────
  { pattern: "AVIVA", category: "Insurance" },
  { pattern: "ADMIRAL", category: "Insurance" },
  { pattern: "DIRECT LINE", category: "Insurance" },
  { pattern: "CHURCHILL INSURANCE", category: "Insurance" },
  { pattern: "CHURCHILL INS", category: "Insurance" },
  { pattern: "HASTINGS DIRECT", category: "Insurance" },
  { pattern: "HASTINGS INS", category: "Insurance" },
  { pattern: "LV INSURANCE", category: "Insurance" },
  { pattern: "LV=", category: "Insurance" },
  { pattern: "AXA", category: "Insurance" },
  { pattern: "AGEAS", category: "Insurance" },
  { pattern: "ESURE", category: "Insurance" },
  { pattern: "VITALITY", category: "Insurance" },
  { pattern: "PETPLAN", category: "Insurance" },
  { pattern: "MORE THAN", category: "Insurance" },
  { pattern: "SAGA INSURANCE", category: "Insurance" },
  { pattern: "AA INSURANCE", category: "Insurance" },
  { pattern: "RAC INSURANCE", category: "Insurance" },
  { pattern: "RAC BREAKDOWN", category: "Insurance" },
  { pattern: "AA MEMBERSHIP", category: "Insurance" },
  { pattern: "GREEN FLAG", category: "Insurance" },
  { pattern: "INSURANCE", category: "Insurance" },
  { pattern: "DVLA", category: "Insurance" }, // vehicle tax — see ambiguity note
  { pattern: "QUOTEMEHAPPY", category: "Insurance" },
  { pattern: "ZEGO", category: "Insurance" },

  // ───────────────────────── Phone & Internet ─────────────────────────
  { pattern: "VODAFONE", category: "Phone & Internet" },
  { pattern: "O2 ", category: "Phone & Internet" },
  { pattern: "EE LIMITED", category: "Phone & Internet" },
  { pattern: "EE TOPUP", category: "Phone & Internet" },
  { pattern: "EE & T-MOBILE", category: "Phone & Internet" },
  { pattern: "GIFFGAFF", category: "Phone & Internet" },
  { pattern: "THREE.CO.UK", category: "Phone & Internet" },
  { pattern: "3 MOBILE", category: "Phone & Internet" },
  { pattern: "HUTCHISON 3G", category: "Phone & Internet" },
  { pattern: "TESCO MOBILE", category: "Phone & Internet" },
  { pattern: "VOXI", category: "Phone & Internet" },
  { pattern: "SMARTY", category: "Phone & Internet" },
  { pattern: "LEBARA", category: "Phone & Internet" },
  { pattern: "LYCAMOBILE", category: "Phone & Internet" },
  { pattern: "SKY MOBILE", category: "Phone & Internet" },
  { pattern: "SKY DIGITAL", category: "Phone & Internet" },
  { pattern: "SKY BROADBAND", category: "Phone & Internet" },
  { pattern: "SKY.COM", category: "Phone & Internet" },
  { pattern: "BT GROUP", category: "Phone & Internet" },
  { pattern: "BT.COM", category: "Phone & Internet" },
  { pattern: "VIRGIN MEDIA", category: "Phone & Internet" },
  { pattern: "PLUSNET", category: "Phone & Internet" },
  { pattern: "TALKTALK", category: "Phone & Internet" },
  { pattern: "NOW BROADBAND", category: "Phone & Internet" },
  { pattern: "ZEN INTERNET", category: "Phone & Internet" },
  { pattern: "HYPEROPTIC", category: "Phone & Internet" },
  { pattern: "COMMUNITY FIBRE", category: "Phone & Internet" },
  { pattern: "VIRGIN MOBILE", category: "Phone & Internet" },
  { pattern: "ID MOBILE", category: "Phone & Internet" },
  { pattern: "ASDA MOBILE", category: "Phone & Internet" },
  { pattern: "GIGACLEAR", category: "Phone & Internet" },
  { pattern: "VONAGE", category: "Phone & Internet" },

  // ───────────────────────── Home & DIY ─────────────────────────
  { pattern: "B&Q", category: "Home & DIY" },
  { pattern: "SCREWFIX", category: "Home & DIY" },
  { pattern: "WICKES", category: "Home & DIY" },
  { pattern: "HOMEBASE", category: "Home & DIY" },
  { pattern: "IKEA", category: "Home & DIY" },
  { pattern: "DUNELM", category: "Home & DIY" },
  { pattern: "TOOLSTATION", category: "Home & DIY" },
  { pattern: "DFS", category: "Home & DIY" },
  { pattern: "SOFOLOGY", category: "Home & DIY" },
  { pattern: "OAK FURNITURE", category: "Home & DIY" },
  { pattern: "EMMA MATTRESS", category: "Home & DIY" },
  { pattern: "EMMA SLEEP", category: "Home & DIY" },
  { pattern: "SHARPS", category: "Home & DIY" },
  { pattern: "HOWDENS", category: "Home & DIY" },
  { pattern: "MAGNET KITCHEN", category: "Home & DIY" },
  { pattern: "WREN KITCHEN", category: "Home & DIY" },
  { pattern: "TOPPS TILES", category: "Home & DIY" },
  { pattern: "JEWSON", category: "Home & DIY" },
  { pattern: "TRAVIS PERKINS", category: "Home & DIY" },
  { pattern: "PLUMBASE", category: "Home & DIY" },
  { pattern: "FURNITURE VILLAGE", category: "Home & DIY" },
  { pattern: "HARVEYS FURNITURE", category: "Home & DIY" },
  { pattern: "MADE.COM", category: "Home & DIY" },
  { pattern: "LA REDOUTE", category: "Home & DIY" },
  { pattern: "DULUX", category: "Home & DIY" },
  { pattern: "LEEKES", category: "Home & DIY" },

  // ───────────────────────── Personal Care ─────────────────────────
  { pattern: "TONI & GUY", category: "Personal Care" },
  { pattern: "SUPERCUTS", category: "Personal Care" },
  { pattern: "REGIS", category: "Personal Care" },
  { pattern: "RUSH HAIR", category: "Personal Care" },
  { pattern: "TREATWELL", category: "Personal Care" },
  { pattern: "THE BODY SHOP", category: "Personal Care" },
  { pattern: "LUSH", category: "Personal Care" },
  { pattern: "SPACE NK", category: "Personal Care" },
  { pattern: "SEPHORA", category: "Personal Care" },
  { pattern: "BARBER", category: "Personal Care" },
  { pattern: "HAIR SALON", category: "Personal Care" },
  { pattern: "NAIL BAR", category: "Personal Care" },
  { pattern: "NAILS", category: "Personal Care" },
  { pattern: "BEAUTY SALON", category: "Personal Care" },
  { pattern: "SPA ", category: "Personal Care" },
  { pattern: "MOLTON BROWN", category: "Personal Care" },
  { pattern: "RITUALS", category: "Personal Care" },
  { pattern: "L'OCCITANE", category: "Personal Care" },
  { pattern: "LOCCITANE", category: "Personal Care" },
  { pattern: "KIKO MILANO", category: "Personal Care" },
  { pattern: "MAC COSMETICS", category: "Personal Care" },

  // ───────────────────────── Kids & Education ─────────────────────────
  { pattern: "MOTHERCARE", category: "Kids & Education" },
  { pattern: "JOJO MAMAN", category: "Kids & Education" },
  { pattern: "EARLY LEARNING", category: "Kids & Education" },
  { pattern: "UDEMY", category: "Kids & Education" },
  { pattern: "COURSERA", category: "Kids & Education" },
  { pattern: "SKILLSHARE", category: "Kids & Education" },
  { pattern: "DUOLINGO", category: "Kids & Education" },
  { pattern: "NURSERY", category: "Kids & Education" },
  { pattern: "CHILDCARE", category: "Kids & Education" },
  { pattern: "PRESCHOOL", category: "Kids & Education" },
  { pattern: "PRE-SCHOOL", category: "Kids & Education" },
  { pattern: "SMIGGLE", category: "Kids & Education" },
  { pattern: "THE ENTERTAINER", category: "Kids & Education" },
  { pattern: "TOYS R US", category: "Kids & Education" },
  { pattern: "LEGO STORE", category: "Kids & Education" },
  { pattern: "TUITION", category: "Kids & Education" },
  { pattern: "STUDENT FINANCE", category: "Kids & Education" },
  { pattern: "OPEN UNIVERSITY", category: "Kids & Education" },
  { pattern: "PEARSON VUE", category: "Kids & Education" },
  { pattern: "KUMON", category: "Kids & Education" },
  { pattern: "EXPLORE LEARNING", category: "Kids & Education" },

  // ───────────────────────── Pets ─────────────────────────
  { pattern: "PETS AT HOME", category: "Pets" },
  { pattern: "VETS4PETS", category: "Pets" },
  { pattern: "VETS 4 PETS", category: "Pets" },
  { pattern: "PDSA", category: "Pets" },
  { pattern: "ZOOPLUS", category: "Pets" },
  { pattern: "PETPLANET", category: "Pets" },
  { pattern: "BOUGHT BY MANY", category: "Pets" },
  { pattern: "JOLLYES", category: "Pets" },
  { pattern: "FETCH", category: "Pets" },
  { pattern: "TAILS.COM", category: "Pets" },
  { pattern: "VETERINARY", category: "Pets" },
  { pattern: "VET SURGERY", category: "Pets" },
  { pattern: "ANIMAL HOSPITAL", category: "Pets" },
  { pattern: "PET SHOP", category: "Pets" },
  { pattern: "MEDIVET", category: "Pets" },

  // ───────────────────────── Travel & Holidays ─────────────────────────
  { pattern: "AIRBNB", category: "Travel & Holidays" },
  { pattern: "BOOKING.COM", category: "Travel & Holidays" },
  { pattern: "EASYJET", category: "Travel & Holidays" },
  { pattern: "RYANAIR", category: "Travel & Holidays" },
  { pattern: "BRITISH AIRWAYS", category: "Travel & Holidays" },
  { pattern: "JET2", category: "Travel & Holidays" },
  { pattern: "TUI", category: "Travel & Holidays" },
  { pattern: "WIZZ AIR", category: "Travel & Holidays" },
  { pattern: "WIZZAIR", category: "Travel & Holidays" },
  { pattern: "VIRGIN ATLANTIC", category: "Travel & Holidays" },
  { pattern: "EXPEDIA", category: "Travel & Holidays" },
  { pattern: "HOTELS.COM", category: "Travel & Holidays" },
  { pattern: "TRIVAGO", category: "Travel & Holidays" },
  { pattern: "PREMIER INN", category: "Travel & Holidays" },
  { pattern: "TRAVELODGE", category: "Travel & Holidays" },
  { pattern: "HOLIDAY INN", category: "Travel & Holidays" },
  { pattern: "HILTON", category: "Travel & Holidays" },
  { pattern: "MARRIOTT", category: "Travel & Holidays" },
  { pattern: "IBIS", category: "Travel & Holidays" },
  { pattern: "EUROSTAR", category: "Travel & Holidays" },
  { pattern: "P&O FERRIES", category: "Travel & Holidays" },
  { pattern: "DFDS", category: "Travel & Holidays" },
  { pattern: "LASTMINUTE", category: "Travel & Holidays" },
  { pattern: "ON THE BEACH", category: "Travel & Holidays" },
  { pattern: "LOVEHOLIDAYS", category: "Travel & Holidays" },
  { pattern: "JET2HOLIDAYS", category: "Travel & Holidays" },
  { pattern: "TUI HOLIDAY", category: "Travel & Holidays" },
  { pattern: "SKYSCANNER", category: "Travel & Holidays" },
  { pattern: "AIR FRANCE", category: "Travel & Holidays" },
  { pattern: "KLM", category: "Travel & Holidays" },
  { pattern: "LUFTHANSA", category: "Travel & Holidays" },
  { pattern: "EMIRATES", category: "Travel & Holidays" },
  { pattern: "QATAR AIRWAYS", category: "Travel & Holidays" },
  { pattern: "JET2.COM", category: "Travel & Holidays" },
  { pattern: "BREWERS FAYRE", category: "Travel & Holidays" },
  { pattern: "PREMIERINN", category: "Travel & Holidays" },
  { pattern: "BRITTANY FERRIES", category: "Travel & Holidays" },
  { pattern: "EUROTUNNEL", category: "Travel & Holidays" },
  { pattern: "LE SHUTTLE", category: "Travel & Holidays" },
  { pattern: "CENTER PARCS", category: "Travel & Holidays" },
  { pattern: "HAVEN HOLIDAY", category: "Travel & Holidays" },
  { pattern: "BUTLINS", category: "Travel & Holidays" },
  { pattern: "PONTINS", category: "Travel & Holidays" },
  { pattern: "RADISSON", category: "Travel & Holidays" },
  { pattern: "TRAVEL REPUBLIC", category: "Travel & Holidays" },

  // ───────────────────────── Charity ─────────────────────────
  { pattern: "JUSTGIVING", category: "Charity" },
  { pattern: "GOFUNDME", category: "Charity" },
  { pattern: "OXFAM", category: "Charity" },
  { pattern: "BRITISH HEART", category: "Charity" },
  { pattern: "CANCER RESEARCH", category: "Charity" },
  { pattern: "BARNARDO", category: "Charity" },
  { pattern: "SHELTER", category: "Charity" },
  { pattern: "RSPCA", category: "Charity" },
  { pattern: "RSPB", category: "Charity" },
  { pattern: "SAVE THE CHILDREN", category: "Charity" },
  { pattern: "RED CROSS", category: "Charity" },
  { pattern: "MACMILLAN", category: "Charity" },
  { pattern: "WATERAID", category: "Charity" },
  { pattern: "COMIC RELIEF", category: "Charity" },
  { pattern: "CHARITY", category: "Charity" },
  { pattern: "DONATION", category: "Charity" },
  { pattern: "WWF", category: "Charity" },
  { pattern: "UNICEF", category: "Charity" },
  { pattern: "CRISIS UK", category: "Charity" },
  { pattern: "MIND CHARITY", category: "Charity" },
  { pattern: "DOGS TRUST", category: "Charity" },
  { pattern: "CATS PROTECTION", category: "Charity" },
  { pattern: "AGE UK", category: "Charity" },
  { pattern: "MARIE CURIE", category: "Charity" },
  { pattern: "SALVATION ARMY", category: "Charity" },

  // ───────────────────────── Cash Withdrawal ─────────────────────────
  { pattern: "CASH WITHDRAWAL", category: "Cash Withdrawal" },
  { pattern: "CASHPOINT", category: "Cash Withdrawal" },
  { pattern: "LINK ATM", category: "Cash Withdrawal" },
  { pattern: "NOTEMACHINE", category: "Cash Withdrawal" },
  { pattern: "CARDTRONICS", category: "Cash Withdrawal" },
  { pattern: "PAYPOINT CASH", category: "Cash Withdrawal" },
  { pattern: "ATM", category: "Cash Withdrawal" },

  // ───────────────────────── Fees & Charges ─────────────────────────
  { pattern: "OVERDRAFT", category: "Fees & Charges" },
  { pattern: "ACCOUNT FEE", category: "Fees & Charges" },
  { pattern: "MONTHLY FEE", category: "Fees & Charges" },
  { pattern: "INTEREST CHARGED", category: "Fees & Charges" },
  { pattern: "BANK CHARGES", category: "Fees & Charges" },
  { pattern: "RETURNED DD", category: "Fees & Charges" },
  { pattern: "LATE PAYMENT", category: "Fees & Charges" },
  { pattern: "NON-STERLING", category: "Fees & Charges" },
  { pattern: "NON STERLING", category: "Fees & Charges" },
  { pattern: "ATM FEE", category: "Fees & Charges" },
  { pattern: "UNPAID ITEM", category: "Fees & Charges" },
  { pattern: "ARRANGED OVERDRAFT", category: "Fees & Charges" },
  { pattern: "SERVICE CHARGE", category: "Fees & Charges" },
  { pattern: "ADMIN FEE", category: "Fees & Charges" },
  { pattern: "CASH ADVANCE FEE", category: "Fees & Charges" },

  // ───────────────────────── Savings & Investments ─────────────────────────
  { pattern: "VANGUARD", category: "Savings & Investments" },
  { pattern: "HARGREAVES LANSDOWN", category: "Savings & Investments" },
  { pattern: "TRADING 212", category: "Savings & Investments" },
  { pattern: "TRADING212", category: "Savings & Investments" },
  { pattern: "FREETRADE", category: "Savings & Investments" },
  { pattern: "MONEYBOX", category: "Savings & Investments" },
  { pattern: "NUTMEG", category: "Savings & Investments" },
  { pattern: "AJ BELL", category: "Savings & Investments" },
  { pattern: "INTERACTIVE INVESTOR", category: "Savings & Investments" },
  { pattern: "NS&I", category: "Savings & Investments" },
  { pattern: "PREMIUM BONDS", category: "Savings & Investments" },
  { pattern: "COINBASE", category: "Savings & Investments" },
  { pattern: "ETORO", category: "Savings & Investments" },
  { pattern: "WEALTHIFY", category: "Savings & Investments" },
  { pattern: "FIDELITY", category: "Savings & Investments" },
  { pattern: "PLUM SAVING", category: "Savings & Investments" },
  { pattern: "CHIP SAVING", category: "Savings & Investments" },
  { pattern: "BINANCE", category: "Savings & Investments" },
  { pattern: "KRAKEN", category: "Savings & Investments" },
  { pattern: "PENSIONBEE", category: "Savings & Investments" },
  { pattern: "SCOTTISH WIDOWS", category: "Savings & Investments" },
  { pattern: "STANDARD LIFE", category: "Savings & Investments" },

  // ───────────────────────── Transfers ─────────────────────────
  // "transfer" type — excluded from spend/income aggregations.
  { pattern: "PAYMENT RECEIVED - THANK YOU", category: "Transfers" },
  { pattern: "THANK YOU - PAYMENT", category: "Transfers" },
  { pattern: "REPAYMENT", category: "Transfers" },
  { pattern: "TRANSFER TO", category: "Transfers" },
  { pattern: "TRANSFER FROM", category: "Transfers" },
  { pattern: "SAVINGS POT", category: "Transfers" },
  { pattern: "POT TRANSFER", category: "Transfers" },
  { pattern: "MONZO-SAVINGS", category: "Transfers" },
  { pattern: "MOVED TO SAVINGS", category: "Transfers" },
  { pattern: "ROUND UP", category: "Transfers" },
  { pattern: "ROUNDUP", category: "Transfers" },
  { pattern: "OWN ACCOUNT", category: "Transfers" },
  { pattern: "VAULT", category: "Transfers" },
  { pattern: "TO SAVINGS", category: "Transfers" },
  { pattern: "INTERNAL TRANSFER", category: "Transfers" },
  { pattern: "BETWEEN ACCOUNTS", category: "Transfers" },

  // ───────────────────────── Salary ─────────────────────────
  { pattern: "SALARY", category: "Salary" },
  { pattern: "WAGES", category: "Salary" },
  { pattern: "PAYROLL", category: "Salary" },
  { pattern: "PAYSLIP", category: "Salary" },
  { pattern: "NET PAY", category: "Salary" },
  { pattern: "MONTHLY PAY", category: "Salary" },

  // ───────────────────────── Other Income ─────────────────────────
  { pattern: "HMRC REPAYMENT", category: "Other Income" },
  { pattern: "HMRC", category: "Other Income" },
  { pattern: "INTEREST PAID", category: "Other Income" },
  { pattern: "DIVIDEND", category: "Other Income" },
  { pattern: "REFUND", category: "Other Income" },
  { pattern: "CASHBACK", category: "Other Income" },
  { pattern: "CHILD BENEFIT", category: "Other Income" },
  { pattern: "UNIVERSAL CREDIT", category: "Other Income" },
  { pattern: "TAX CREDIT", category: "Other Income" },
  { pattern: "PENSION CREDIT", category: "Other Income" },
  { pattern: "STATE PENSION", category: "Other Income" },
  { pattern: "REBATE", category: "Other Income" },
];

/** Convenience: builtin entries as UserRule-shaped objects (pattern + name). */
export const BUILTIN_RULES: UserRule[] = UK_MERCHANTS.map((m) => ({
  pattern: m.pattern,
  categoryName: m.category,
}));
